common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views 

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from stay import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stay/',include('stay.urls')),
    path('review/',include('review.urls')),
    path('common/',include('common.urls')),
    path('',views.Stay),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views

app_name='review'
urlpatterns = [
    path('', views.ReviewList.as_view(), name='list'),
    path('<int:pk>/', views.ReviewDetail.as_view(), name='detail'),
    path('create_review/', views.ReviewCreate.as_view(),name='review_create'),
    path('delete_review/<int:pk>/', views.ReviewDelete,name='review_delete'),
    path('update_review/<int:pk>/', views.ReviewUpdate.as_view(),name='review_update'),
]

stay/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='stay'
urlpatterns =[
    path('detail1/',views.Detail1,name='detail1'),
    path('detail2/',views.Detail2,name='detail2'),
    path('detail3/',views.Detail3,name='detail3'),
    path('',views.Stay,name='stay'),
]

common/models.py
from django.db import models

# Create your models here.

review/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Review(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  file_upload = models.FileField(upload_to='review/data/%Y/%m/%d/', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
    return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/review/{self.pk}/'

stay/models.py
from django.db import models

# Create your models here.

common/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

review/forms.py
from django import forms
from .models import Review
from django.utils.safestring import mark_safe

class CustomFileWidget(forms.FileInput):
  def __init__(self, attrs={}):
      super().__init__(attrs)

  def render(self, name, value, attrs=None, renderer=None):
    print(value, name)
    output = []
    if value and hasattr(value, "url"):
      file_name = value.url.split('/')[-1]
      output.append(super().render(name, value, attrs))
      output.append(f'<span class="form-control">첨부파일 : <a class="text-reset text-decoration-none" target="_blank" href="{value.url}">{file_name}</a><input class="form-check-input ms-2 me-1" type="checkbox" name="upload_clear" id="upload_clear_id" value="upload_del">Delete</span>')
      return mark_safe(u''.join(output))
    output.append(super().render(name, value, attrs))
    return mark_safe(u''.join(output))

class ReviewUpdateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  
  class Meta:
    model = Review
    fields = ('title', 'file_upload', 'content')
    widgets = {
      'file_upload': CustomFileWidget,
    }


class ReviewCreateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  class Meta:
    model = Review
    fields = ('title', 'file_upload', 'content')

common/views.py
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
  if request.method == "POST":
    form = UserForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=raw_password)
      login(request, user) 
      return redirect('/')
  else:
      form = UserForm()
  return render(request, 'common/signup.html', {'form': form})

review/views.py
from django.shortcuts import get_object_or_404, render, redirect
from review.models import Review
from review.forms import ReviewCreateForm, ReviewUpdateForm
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from django.contrib.auth.decorators import login_required
from config import settings
import os

from django.core.exceptions import PermissionDenied
class ReviewUpdate(UpdateView):
    model = Review
    form_class = ReviewUpdateForm
    template_name = 'review/review_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        if self.get_object().file_upload.name != '':
            if self.object.file_upload != self.get_object().file_upload.name:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
            if 'upload_clear' in self.request.POST:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
                    self.object.file_upload = ''
        return super().form_valid(form)


class ReviewList(ListView):
    model = Review
    template_name = 'review/review_list.html'
    ordering = '-pk'
    paginate_by = 10

class ReviewDetail(DetailView):
    model = Review
    template_name = 'review/review_detail.html'

class ReviewCreate(CreateView):
    model = Review
    form_class = ReviewCreateForm
    template_name = 'review/review_form.html'
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/review')

@login_required(login_url='common:login')
def ReviewDelete(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user != review.author:
        return redirect('review:detail', pk=pk)
    if review.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, review.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    review.delete()
    return redirect('review:list')

stay/views.py
from django.shortcuts import render

# Create your views here.

def Detail1(request):
    return render(request,'stay/detail1.html')

def Detail2(request):
    return render(request,'stay/detail2.html')

def Detail3(request):
    return render(request,'stay/detail3.html')

def Stay(request):
    return render(request,'stay/stay.html')

templates/common/login.html
{% extends "stay_base.html" %}
{% block content %}
<section data-bs-version="5.1" class="form7 cid-twoviCRZxQ" id="form7-20">
    
    
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong><span style="font-family: 'Lilita One',cursive; font-size:50px;">STAY</span></strong>
            </h3>
            
        </div>
        <br><br>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form action="#" method="POST" class="mbr-form form-with-styler mx-auto" data-form-title="Form Name">
                    {% csrf_token %}
                    {% include 'form_errors.html' %}
                    <div class="dragArea row">
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="text" class="form-control" name="username" id="username"
                            placeholder="Enter User ID" value="{{ form.username.value | default_if_none:'' }}">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="password" class="form-control" name="password" id="password" 
                            placeholder="Enter User Password" value="{{ form.password.value | default_if_none:'' }}">
                        </div>
                        <div class="col-auto mbr-section-btn align-center">
                            <button type="submit" class="btn btn-warning">LOGIN</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/common/signup.html
{% extends "stay_base.html" %}
{% block content %}
<section data-bs-version="5.1" class="form7 cid-twoviCRZxQ" id="form7-20">
    
    
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong><span style="font-family: 'Lilita One',cursive; font-size: 30px;">SIGN UP</span></strong>
            </h3>
            
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form method="POST" class="mbr-form form-with-styler mx-auto" data-form-title="Form Name">
                    <p class="mbr-text mbr-fonts-style align-center mb-4 display-7">
                        One of our team will be in contact with you shortly.
                    </p>
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="dragArea row">
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="text" class="form-control" name="username" id="username" placeholder="ID" 
                            value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="password" class="form-control" name="password1" id="password1" placeholder="Password" 
                            value="{{ form.password1.value|default_if_none:'' }}">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="password" class="form-control" name="password2" id="password2" placeholder="Re-Entry Password" 
                            value="{{ form.password2.value|default_if_none:'' }}">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="email" class="form-control" name="email" id="email" placeholder="E-mail Address" 
                            value="{{ form.email.value|default_if_none:'' }}">
                        </div>
                        <div class="col-auto mbr-section-btn align-center">
                            <button type="submit" class="btn btn-warning"><span style="font-family: 'Lilita One',cursive; font-size: 30px;">Submit</span></button>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<!-- Field Input Error -->
{% for field in form %}
  {% for error in field.errors %}
    <div class="alert alert-danger">
      <strong>{{ field.label }} </strong>{{ error }}
    </div>
  {% endfor %}
{% endfor %}

<!-- Non Field Error -->
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    <strong>{{ error }}</strong>
  </div>
{% endfor %} 
{% endif %}

templates/review/review_detail.html
{% extends "stay_base.html" %}
<head>
    
      <title>Stay_Review</title>
</head>
{% block content %}
<section class="board_detail-block">
    <div class="container mt-5">
    <div class="card border-dark mb-3">
  
      <div class="card-header">
        <h4 class="pt-1">{{ object.title }}</h4>
        {% if object.modify_date %}
          <p class="pt-1">Created by {{ object.author }} on {{ object.modify_date }}</p>
        {% else %}
          <p class="pt-1">Created by {{ object.author }} on {{ object.create_date }}</p>
        {% endif %}
      </div>
      
      <div class="card-header">
        {% if object.file_upload %}
        <a href="{{ object.file_upload.url }}" class="text-decoration-none text-muted" role="button" download>
          첨부파일 : <i class="fa-solid fa-file-lines me-2"></i>{{object.get_FileName}}
        </a>
        {% else %}
        <a class="text-decoration-none text-muted">첨부파일 : </a>
        {% endif %}
      </div>
  
      <div class="card-body text-dark">
        <p class="card-text">{{ object.content | linebreaksbr }}</p>
        <div class="mt-4"></div>
      </div>
      
      <div class="card-footer d-flex justify-content-between">
        <a href="{% url 'review:list'  %}" class="btn btn-outline-dark">목록</a>
        {% if user == object.author %}
        <span>
          <a href="{% url 'review:review_update' object.id %}" class="btn btn-outline-dark">수정</a>
          <a href="#" class="delete btn btn-outline-dark" data-uri="{% url 'review:review_delete' object.id %}">삭제</a>
        </span>
        {% else %}
        <span>
          <a href="#" class="user_check btn btn-outline-dark">수정</a>
          <a href="#" class="user_check btn btn-outline-dark">삭제</a>
        </span>
        {% endif %}
      </div>
  
      
    </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br>
  </section>
{% endblock %}


{% block script %}

<script type='text/javascript'>
  $(document).ready(function() {
    $(".delete").on('click', function() {
      if(confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data('uri');
      }
    });
  });
  $(document).ready(function() {
    $(".user_check").on('click', function() {
      alert("자신의 게시글만 수정 및 삭제가 가능합니다.")
    });
  });
</script>

{% endblock %}

templates/review/review_form.html
{% extends "stay_base.html" %}
<head>
    
      <title>Stay_Review</title>
</head>
{% block content %}
<section class="board_form-block">
    <div class="container mt-5">
    
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card">
          <div class="card-header input-group">
            <span class="input-group-text">제목 입력</span>
            {{ form.title }}
          </div>
          <div class="card-header input-group">
            {{ form.file_upload }}
          </div>
          <div class="card-body">
            {{ form.content }}
          </div>
          <button type="submit" class="btn btn-outline-dark">게시글 등록</button>
        </div>
      </form>
      <br><br><br><br>
    </div>
</section>
{% endblock %}

templates/review/review_form_update.html
{% extends "stay_base.html" %}
<head>
    <style>
        .pagination > li > a
        {
          background-color: white;
          color: #000;
        }
        .pagination > .active > a
        {
            color: white;
            background-color: #212529 !Important;
            border: solid 1px #212529 !Important;
        }
      </style>
      <title>Stay_Review</title>
</head>
{% block content %}
<section class="board_form-block">
    <div class="container mt-5">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card">
          <div class="card-header input-group">
            <span class="input-group-text">제목 입력</span>
            {{ form.title }}
          </div>
          <div class="card-header input-group">
            {{ form.file_upload }}
          </div>
          <div class="card-body">
            {{ form.content }}
          </div>
          <button type="submit" class="btn btn-outline-dark">게시글 수정</button>
        </div>
      </form>
      
    </div>
</section>

{% endblock %}

templates/review/review_list.html
{% extends "stay_base.html" %}
<head>
    <style>
        .pagination > li > a
        {
          background-color: white;
          color: #000;
        }
        .pagination > .active > a
        {
            color: white;
            background-color: #212529 !Important;
            border: solid 1px #212529 !Important;
        }
    </style>
    <title>Stay_Review</title>
</head>
{% block content %}
<div class="mbr-section-btn item-footer mt-2"><a href="{% url 'review:review_create'%}" class="btn btn-warning" target="_blank">
  <span style="font-family: 'Black Han Sans',sans-serif;"">리뷰 쓰러 가기&gt;</span></a>
</div>
<div class="container mt-5">
    <table class="table table-striped">
      <!-- Table Head 영역 -->
      <thead class="thead-dark">
        <tr class="text-center">
          <th>번호</th>
          <th style="width:50%">제목</th>
          <th>작성자</th>
          <th>작성일</th>
        </tr>
      </thead>
  
      <!-- Table Body 영역 -->
      <tbody>
        {% for stay in object_list %}
        <tr class="text-center">
          <td>{{ stay.id }}</td>
          {% if user.is_authenticated %}
            <td><a class="text-reset text-decoration-none" href="{{ stay.get_absolute_url }}">
            {{ stay.title }}</a></td>
          {% else %}
            <td><a class="login_check text-reset text-decoration-none">
            {{ stay.title }}</a></td>
          {% endif %}
          <td>{{ stay.author }}</td>
          {% if object.modify_date %}
          <td>{{ stay.modify_date }}</td>
          {% else %}
          <td>{{ stay.create_date }}</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
      
      </table><br>
  
    {% if page_obj.paginator.count >= page_obj.paginator.per_page %}
    <!-- pagination 영역 -->
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1"> &lt;&lt; </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
      </li>
      {% else %}
      <li class="page-item disalbed"><a class="page-link" href="#">이전</a></li>
      {% endif %}
      
      {% for page_number in page_obj.paginator.page_range %}
      {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
        {% if page_number == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
      {% endfor %}
  
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> &gt;&gt; </a>
      </li>
      {% else %}
      <li class="page-item disalbed"><a class="page-link" href="#">다음</a></li>
      {% endif %}
    </ul>
    {% endif %}
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
  {% endblock %}
  
  
  <!--jquery cnd 추가후 사용 가능 , 로그인하지 않고 클릭시 오류메세지 뜨게하는 기능-->
  {% block script %}
  <script type='text/javascript'>
    $(document).ready(function() {
      $(".login_check").on('click', function() {
        alert("로그인 후 이용이 가능합니다.")
      });
    });
  </script>

{% endblock %}

templates/stay_base.html
<!DOCTYPE html>
{% load static %}
<html  >
<head>
  
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.8.0, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{%static "assets/images/logo.png"%}" type="image/x-icon">
  <meta name="description" content="">
  
    <!-- Jquery CDN URL -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
  <title>Page 1</title>
  <link rel="stylesheet" href="{%static "assets/web/assets/mobirise-icons2/mobirise2.css"%}">
  <link rel="stylesheet" href="{%static "assets/bootstrap/css/bootstrap.min.css"%}">
  <link rel="stylesheet" href="{%static "assets/bootstrap/css/bootstrap-grid.min.css"%}">
  <link rel="stylesheet" href="{%static "assets/bootstrap/css/bootstrap-reboot.min.css"%}">
  <link rel="stylesheet" href="{%static "assets/dropdown/css/style.css"%}">
  <link rel="stylesheet" href="{%static "assets/socicon/css/styles.css"%}">
  <link rel="stylesheet" href="{%static "assets/theme/css/style.css"%}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{%static "assets/mobirise/css/mbr-additional.css"%}">
  <link rel="stylesheet" href="{%static "assets/mobirise/css/mbr-additional.css"%}" type="text/css">

    <!-- 구글 폰트 링크 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
  
  
</head>

<body>
    {% include "stay_navbar.html" %}
    {% block content %}
    {% endblock %}
    <br><br><br><br><br><br><br>
    <section data-bs-version="5.1" class="footer3 cid-twojD45kAo" once="footers" id="footer3-s">

    

    

        <div class="container">
            <div class="media-container-row align-center mbr-white">
                <div class="row row-links">
                    <ul class="foot-menu">
                        
                        
                        
                        
                        
                    <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">About us</a>
                        </li><li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Services</a>
                        </li><li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Contact Us</a>
                        </li><li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Careers</a>
                        </li><li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Work</a>
                        </li></ul>
                </div>
                <div class="row social-row">
                    <div class="social-list align-right pb-2">
                        
                        
                        
                        
                        
                        
                    <div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-googleplus socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a href="#" target="_blank">
                                <span class="socicon-behance socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div></div>
                </div>
                <div class="row row-copirayt">
                    <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                        © Python Django
                    </p>
                </div>
            </div>
        </div>
    </section>

    {% block script %}
    {% endblock %}
    <script src="{%static "assets/bootstrap/js/bootstrap.bundle.min.js"%}"></script>  
    <script src="{%static "assets/smoothscroll/smooth-scroll.js"%}"></script>  
    <script src="{%static "assets/ytplayer/index.js"%}"></script>  
    <script src="{%static "assets/dropdown/js/navbar-dropdown.js"%}"></script>  
    <script src="{%static "assets/embla/embla.min.js"%}"></script>  
    <script src="{%static "assets/embla/script.js"%}"></script>  
    <script src="{%static "assets/theme/js/script.js"%}"></script>  
    <script src="{%static "assets/countdown/countdown.js"%}"></script>  
    <script src="{%static "assets/formoid/formoid.min.js"%}"></script>  


    
</body>

</html>

templates/stay_navbar.html
{% load static %}

<section data-bs-version="5.1" class="menu menu2 cid-twoiE0QanY" once="menu" id="menu2-n">
    
    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'stay:stay'%}">
                        <img src="{%static "assets/images/logo.png"%}" style="height: 3rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="{% url 'stay:stay'%}"><span style="font-family: 'Lilita One',cursive; font-size: 50px;">STAY</span></a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'stay:detail1'%}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">OCEAN</span></a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'stay:detail2'%}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">NATURE</span></a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'stay:detail3'%}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">CITY</span></a>
                    </li>
                    
                </ul>
                {% if user.is_anonymous %}
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-warning" href="{% url 'common:login' %}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">LOGIN</span></a>
                </div>
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-warning" href="{% url 'common:signup' %}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">SIGNUP</span></a>
                </div>
                {% else %}
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-warning" href="{% url 'review:list' %}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">REVIEW</span></a>
                </div>
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-warning" href="{% url 'common:logout' %}">
                        <span style="font-family: 'Lilita One',cursive; font-size: 30px;">LOGOUT</span></a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
</section>